name: Generate SBOM

on:
  push:
    branches: ["main"]

jobs:
  sbom:
    name: Generate CycloneDX SBOM
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Generate SBOM with Syft
        uses: anchore/sbom-action@v0
        with:
          path: ./task-d-dynamictesting/webapp
          format: cyclonedx-json
          output-file: sbom.cdx.json
          artifact-name: sbom.cdx.json
